//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.06 at 03:09:43 PM CET 
//


package webApplication.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CINodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CINodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://musium.org/catree}CAandxor"/>
 *         &lt;element name="Necessity" type="{http://musium.org/catree}CAZeroOne" minOccurs="0"/>
 *         &lt;element name="Relevance" type="{http://musium.org/catree}CAZeroOne" minOccurs="0"/>
 *         &lt;element name="Coverage" type="{http://musium.org/catree}CAZeroOne" minOccurs="0"/>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="ECI" type="{http://musium.org/catree}ECIType"/>
 *           &lt;element name="CINode" type="{http://musium.org/catree}CINodeType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CINodeType", propOrder = {
    "id",
    "type",
    "necessity",
    "relevance",
    "coverage",
    "category",
    "eciOrCINode"
})
public class CINodeType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Type", required = true)
    protected CAandxor type;
    @XmlElement(name = "Necessity")
    protected BigDecimal necessity;
    @XmlElement(name = "Relevance")
    protected BigDecimal relevance;
    @XmlElement(name = "Coverage")
    protected BigDecimal coverage;
    @XmlElement(name = "Category")
    protected String category;
    @XmlElements({
        @XmlElement(name = "CINode", type = CINodeType.class),
        @XmlElement(name = "ECI", type = ECIType.class)
    })
    protected List<Object> eciOrCINode;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CAandxor }
     *     
     */
    public CAandxor getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAandxor }
     *     
     */
    public void setType(CAandxor value) {
        this.type = value;
    }

    /**
     * Gets the value of the necessity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNecessity() {
        return necessity;
    }

    /**
     * Sets the value of the necessity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNecessity(BigDecimal value) {
        this.necessity = value;
    }

    /**
     * Gets the value of the relevance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelevance() {
        return relevance;
    }

    /**
     * Sets the value of the relevance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelevance(BigDecimal value) {
        this.relevance = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoverage(BigDecimal value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the eciOrCINode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eciOrCINode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getECIOrCINode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CINodeType }
     * {@link ECIType }
     * 
     * 
     */
    public List<Object> getECIOrCINode() {
        if (eciOrCINode == null) {
            eciOrCINode = new ArrayList<Object>();
        }
        return this.eciOrCINode;
    }

}
