//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.06 at 03:09:43 PM CET 
//


package webApplication.xml;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the webApplication.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
	
	private static final String ROOTID = "001";
	private static final String ROOTNECESSITY = "1.00";
	private static final String ROOTRELEVANCE = "1.00";


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: webApplication.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ECIType }
     * 
     */
    public ECIType createECIType() {
        return new ECIType();
    }

    /**
     * Create an instance of {@link CINodeType }
     * 
     */
    public CINodeType createCINodeType() {
        return new CINodeType();
    }

    /**
     * Create an instance of {@link CARoot }
     * 
     */
    public CARoot createCARoot() {
    	CARoot root = new CARoot();
    	root.setID(ROOTID);
    	root.setType(CAandxor.AND);
    	root.setNecessity(new BigDecimal(ROOTNECESSITY));
    	root.setRelevance(new BigDecimal(ROOTRELEVANCE));
        return root;
    }

}
